export const types = {
  onBoardFinished: 'onBoardFinished',
  isLoadingTrue: 'isLoadingTrue',
  isLoadingFalse: 'isLoadingFalse',
  isAlertTrue: 'isAlertTrue',
  isAlertFalse: 'isAlertFalse',
  LoginType: 'LoginType',
  LogoutType: 'LogoutType',
  LogoutFirebaseType: 'LogoutFirebaseType',
  RegisterUser: 'RegisterUser',
  UpdateAuth: 'UpdateAuth',
  UpdateProfile: 'UpdateProfile',
  addPlan: 'AddPlan',
  ClearPlan: 'ClearPlan',
  UpdatePlan: 'UpdatePlan',
  forgotPasswordType: 'forgotPasswordType',
};
