import {StyleSheet} from 'react-native';
import {hp, wp} from '../../Config/responsive';
import {Colors} from '../../Theme/Variables';

export const styles = StyleSheet.create({
  StepsMain: {
    flexGrow: 1,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: hp('3'),
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp('100'),
    paddingHorizontal: wp('4'),
    position: 'absolute',
    bottom: 30,
  },
  button: {
    paddingVertical: hp('1'),
    paddingHorizontal: wp('4'),
    borderRadius: 30,
    fontSize: hp('1'),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('.2'),
  },
  buttonText: {
    fontSize: hp('1.8'),
    color: 'white',
  },
  arrRight: {
    width: wp('4'),
    height: hp('2'),
    resizeMode: 'contain',
    marginLeft: wp('1.5'),
  },
  previousButton: {
    backgroundColor: Colors.primaryColor,
  },
  nextButton: {
    backgroundColor: Colors.primaryColor,
  },
  stepIndicator: {
    fontSize: 20,
    marginBottom: 20,
  },
  stepCirclesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: wp('5'),
  },
  circleContainer: {
    alignItems: 'center',
    marginHorizontal: wp('2.5'),
  },
  circle: {
    width: wp('10'),
    height: hp('5'),
    borderRadius: 20,
    backgroundColor: '#EBD5F2',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  activeCircle: {
    backgroundColor: Colors.primaryColor,
  },
  circleText: {
    fontSize: hp('3'),
    fontWeight: '800',
    color: 'white',
  },
  activeLine: {
    backgroundColor: Colors.primaryColor,
  },
  nonActiveLine: {
    flex: 1,
    height: hp('.6'),
    backgroundColor: '#EBD5F2',
    position: 'absolute',
    left: 30,
    right: 20,
    top: 18,
    width: wp('10'),
    zIndex: 0,
  },
  content: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  tagline: {
    color: '#525252',
    paddingHorizontal: wp('8'),
    textAlign: 'center',
    marginBottom: hp('8'),
  },
  categories: selectedCategory => ({
    borderWidth: 1,
    borderColor: selectedCategory ? Colors.themeGreen : '#525252',
    borderRadius: 20,
    width: wp('44'),
    paddingHorizontal: wp('2'),
    paddingVertical: hp('3'),
    alignItems: 'center',
    marginTop: hp('2'),
    backgroundColor: selectedCategory ? Colors.themeGreen : 'transparent',
  }),
  mainContent: {
    width: wp('100'),
    paddingHorizontal: wp('4'),
  },
  catImage: selectedCategory => ({
    width: wp('17'),
    height: hp('8.5'),
    resizeMode: 'contain',
    alignSelf: 'center',
    tintColor: selectedCategory ? 'white' : null,
  }),
  catTitle: selectedCategory => ({
    fontSize: hp('2.6'),
    fontWeight: '700',
    color: selectedCategory ? 'white' : Colors.primaryColor,
    marginTop: hp('2'),
  }),
  title: {
    fontSize: hp('3.5'),
    fontWeight: '700',
    color: Colors.primaryColor,
    textAlign: 'center',
    marginBottom: hp('3'),
  },
  titleStepTwo: {
    fontSize: hp('3.5'),
    fontWeight: '700',
    color: Colors.primaryColor,
    textAlign: 'center',
    marginBottom: hp('0'),
  },
  titleSubText: {
    fontSize: hp('2.6'),
    fontWeight: '700',
    color: Colors.primaryColor,
    marginTop: hp('0'),
    textAlign: 'center',
  },
  stepTwoStyle: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  inputMain: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#525252',
    borderRadius: 30,
    paddingHorizontal: wp('4'),
    width: wp('92'),
    marginVertical: hp('5'),
  },
  inputStyle: {
    width: wp('73'),
  },
  inputImage: {
    width: wp('6'),
    resizeMode: 'contain',
    marginRight: wp('2'),
  },
  btnStepMain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  btnMain: {
    borderRadius: 30,
    borderWidth: 1,
    borderColor: Colors.themeGreen,
    height: hp('4.5'),
    width: 'auto',
    paddingHorizontal: wp('4.7'),
    marginRight: wp('2'),
    marginBottom: hp('1'),
  },
  btnText: {
    color: '#525252',
  },
  gender: selectedGender => ({
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: selectedGender ? Colors.themeGreen : '#525252',
    borderRadius: 20,
    width: wp('92'),
    paddingHorizontal: wp('4'),
    paddingVertical: hp('2'),
    alignItems: 'center',
    marginBottom: hp('3.5'),
    backgroundColor: selectedGender ? Colors.themeGreen : 'transparent',
  }),
  genderTitle: selectedGender => ({
    fontSize: hp('2.2'),
    color: selectedGender ? 'white' : '#525252',
  }),
  catImage: selectedGender => ({
    width: wp('12'),
    height: hp('6'),
    resizeMode: 'contain',
    alignSelf: 'center',
    tintColor: selectedGender ? 'white' : null,
    marginRight: wp('6'),
  }),
  lastTagline: {
    color: '#525252',
    paddingHorizontal: wp('8'),
    textAlign: 'center',
    marginBottom: hp('4'),
  },
  titleLastStep: {
    fontSize: hp('3.5'),
    fontWeight: '700',
    color: Colors.primaryColor,
    textAlign: 'center',
    marginBottom: hp('3'),
    paddingHorizontal: wp('8'),
  },
  agePicker: {
    borderWidth: 1,
    borderColor: '#525252',
    borderRadius: 30,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  titleStep4: {
    fontSize: hp('3.5'),
    fontWeight: '700',
    color: Colors.primaryColor,
    textAlign: 'center',
    marginBottom: hp('5'),
  },

  pickerText: pickerText => ({
    color: pickerText ? 'black' : '#525252',
    paddingHorizontal: wp('5'),
    paddingVertical: hp('.5'),
    position: 'absolute',
    width: wp('40'),
    fontSize: hp('1.8'),
    opacity: 0.9,
  }),
  hideBorder: {
    borderWidth: 0,
    borderColor: 'transparent',
  },
});
