import {Platform, StyleSheet} from 'react-native';
import {hp, wp} from '../../Config/responsive';
import {Colors} from '../../Theme/Variables';

export const styles = StyleSheet.create({
  StepsMain: {
    flexGrow: 1,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    paddingTop: hp('3'),
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: wp('100'),
    paddingHorizontal: wp('4'),
    position: 'absolute',
    bottom: 30,
  },
  button: {
    paddingVertical: hp('1'),
    paddingHorizontal: wp('4'),
    borderRadius: 30,
    fontSize: hp('1'),
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: hp('.2'),
  },
  buttonText: {
    fontSize: hp('1.8'),
    color: 'white',
  },
  arrRight: {
    width: wp('4'),
    height: hp('2'),
    resizeMode: 'contain',
    marginLeft: wp('1.5'),
  },
  previousButton: {
    backgroundColor: Colors.primaryColor,
  },
  nextButton: {
    backgroundColor: Colors.primaryColor,
  },
  stepIndicator: {
    fontSize: 20,
    marginBottom: 20,
  },
  stepCirclesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: wp('5'),
  },
  circleContainer: {
    alignItems: 'center',
    marginHorizontal: wp('2.5'),
  },
  circle: {
    width: wp('10'),
    height: hp('5'),
    borderRadius: 20,
    backgroundColor: '#EBD5F2',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  activeCircle: {
    backgroundColor: Colors.primaryColor,
  },
  circleText: {
    fontSize: hp('3'),
    fontWeight: '800',
    color: 'white',
  },
  activeLine: {
    backgroundColor: Colors.primaryColor,
  },
  nonActiveLine: {
    flex: 1,
    height: hp('.6'),
    backgroundColor: '#EBD5F2',
    position: 'absolute',
    left: 30,
    right: 20,
    top: 18,
    width: wp('10'),
    zIndex: 0,
  },
  tagline: {
    color: '#525252',
    paddingHorizontal: wp('8'),
    textAlign: 'center',
    marginBottom: hp('8'),
  },
  mainContent: {
    width: wp('100'),
    paddingHorizontal: wp('4'),
  },
  // content: {
  //   flexDirection: 'row',
  //   flexWrap: 'wrap',
  //   justifyContent: 'space-between',
  // },

  // categories: selectedCategory => ({
  //   borderWidth: 1,
  //   borderColor: selectedCategory ? Colors.themeGreen : '#525252',
  //   borderRadius: 20,
  //   width: wp('44'),
  //   paddingHorizontal: wp('2'),
  //   paddingVertical: hp('3'),
  //   alignItems: 'center',
  //   marginTop: hp('2'),
  //   backgroundColor: selectedCategory ? Colors.themeGreen : 'transparent',
  // }),
  // purposeImage: selectedCategory => ({
  //   width: wp('17'),
  //   height: hp('8'),
  //   resizeMode: 'contain',
  //   alignSelf: 'center',
  //   tintColor: selectedCategory ? 'white' : null,
  // }),
  // catTitle: selectedCategory => ({
  //   fontSize: hp('2.6'),
  //   fontWeight: '700',
  //   color: selectedCategory ? 'white' : Colors.primaryColor,
  //   marginTop: hp('2'),
  // }),
  // title: {
  //   fontSize: hp('3.5'),
  //   fontWeight: '700',
  //   color: Colors.primaryColor,
  //   textAlign: 'center',
  //   marginBottom: hp('3'),
  // },
  titleStepTwo: {
    fontSize: hp('3.5'),
    fontWeight: '700',
    color: Colors.primaryColor,
    textAlign: 'center',
    marginBottom: hp('0'),
  },
  // titleSubText: {
  //   fontSize: hp('2.6'),
  //   fontWeight: '700',
  //   color: Colors.primaryColor,
  //   marginTop: hp('0'),
  //   textAlign: 'center',
  // },
  // stepTwoStyle: {
  //   flexDirection: 'row',
  //   flexWrap: 'wrap',
  //   justifyContent: 'center',
  // },
  // btnTextTwo: {
  //   width: wp('66'),
  // },
  // inputMain: {
  //   flexDirection: 'row',
  //   justifyContent: 'space-between',
  //   alignItems: 'center',
  //   borderWidth: 1,
  //   borderColor: '#525252',
  //   borderRadius: 30,
  //   paddingHorizontal: wp('4'),
  //   width: wp('92'),
  //   marginVertical: hp('5'),
  // },
  inputStyle: {
    width: wp('73'),
  },
  inputImage: {
    width: wp('6'),
    resizeMode: 'contain',
    marginRight: wp('0'),
  },
  arrowImage: {
    width: wp('5'),
    resizeMode: 'contain',
    marginRight: wp('1'),
  },
  btnStepMain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  btnMain: {
    borderRadius: 30,
    borderWidth: 1,
    borderColor: Colors.themeGreen,
    height: hp('4.5'),
    width: 'auto',
    paddingHorizontal: wp('4.7'),
    marginRight: wp('2'),
    marginBottom: hp('1'),
  },
  btnText: {
    color: '#525252',
  },
  gender: selectedGender => ({
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: selectedGender ? Colors.themeGreen : '#525252',
    borderRadius: 20,
    width: wp('92'),
    paddingHorizontal: wp('4'),
    paddingVertical: hp('2'),
    alignItems: 'center',
    marginBottom: hp('3.5'),
    backgroundColor: selectedGender ? Colors.themeGreen : 'transparent',
  }),
  genderTitle: selectedGender => ({
    fontSize: hp('2.2'),
    color: selectedGender ? 'white' : '#525252',
  }),
  catImage: selectedGender => ({
    width: wp('12'),
    height: hp('6'),
    resizeMode: 'contain',
    alignSelf: 'center',
    tintColor: selectedGender ? 'white' : null,
    marginRight: wp('6'),
  }),
  lastTagline: {
    color: '#525252',
    paddingHorizontal: wp('8'),
    textAlign: 'center',
    marginBottom: hp('4'),
  },
  titleLastStep: {
    fontSize: hp('3.5'),
    fontWeight: '700',
    color: Colors.primaryColor,
    textAlign: 'center',
    marginBottom: hp('3'),
    paddingHorizontal: wp('8'),
  },
  agePicker: {
    borderWidth: 1,
    borderColor: '#525252',
    borderRadius: 30,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  titleStep4: {
    fontSize: hp('3.5'),
    fontWeight: '700',
    color: Colors.primaryColor,
    textAlign: 'center',
    marginBottom: hp('5'),
  },

  pickerText: pickerText => ({
    color: pickerText ? 'black' : '#525252',
    paddingHorizontal: wp('5'),
    paddingVertical: hp('.5'),
    position: 'absolute',
    width: wp('40'),
    fontSize: hp('1.8'),
    opacity: 0.9,
  }),
  hideBorder: {
    borderWidth: 0,
    borderColor: 'transparent',
  },
  searchMain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#525252',
    borderRadius: 30,
    paddingHorizontal: wp('4'),
    width: wp('92'),
    marginVertical: hp('1'),
    marginBottom: hp('2'),
  },
  headerMain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp('1'),
    marginTop: Platform.OS == 'ios' ? hp('3') : 0,
  },
  arrBack: {
    resizeMode: 'contain',
    width: wp('6'),
    height: hp('3'),
  },
  saveText: {
    color: Colors.primaryColor,
  },
  titleMain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: hp('2'),
    // borderTopWidth: 0.2,
    // marginBottom: hp('2'),
  },
  border: {
    borderBottomWidth: 0.2,
    paddingVertical: hp('1'),
  },
  chev: {
    resizeMode: 'contain',
    width: wp('2.4'),
  },
  titleStyle: {
    color: Colors.primaryColor,
    fontSize: hp('1.8'),
    fontWeight: '600',
  },
  item: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    height: hp('4'),
    borderRadius: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: Colors.themeGreen,
    paddingHorizontal: wp('3'),
    marginHorizontal: wp('1'),
    marginVertical: hp('.5'),
  },
  selectedItem: {
    backgroundColor: Colors.themeGreen,
  },
  itemText: {
    color: Colors.textGrayColor,
  },
  activeItemText: {
    color: Colors.white,
  },
  collapseMain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: wp('90'),
  },
  // infoStyle: {
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   alignSelf: 'center',
  // },
  // infoImg: {
  //   width: wp('6'),
  //   height: hp('3'),
  //   resizeMode: 'contain',
  //   marginBottom: hp('-.5'),
  //   position: 'absolute',
  //   left: 20,
  //   top: -8,
  // },
  // modal style
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    paddingVertical: hp('2'),
    paddingBottom: hp('5'),
    paddingHorizontal: wp('3'),
    borderRadius: 10,
    marginHorizontal: wp('5'),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,

    elevation: 9,
  },
  modalHd: {
    fontSize: hp('3.5'),
    fontWeight: '700',
    color: Colors.primaryColor,
    textAlign: 'center',
    marginBottom: hp('1'),
  },
  modalText: {
    fontSize: hp('1.8'),
    textAlign: 'center',
    marginHorizontal: wp('2'),
    lineHeight: 19,
  },
  closeBtn: {
    alignItems: 'flex-end',
  },
  closeIconStyle: {
    resizeMode: 'contain',
    width: wp('6'),
    height: hp('3'),
    marginBottom: hp('-1'),
  },
  btnsMain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: wp('80'),
  },
  allergiesBtns: {
    // backgroundColor: 'rgba(255, 255, 255, 0.3)',
    height: hp('4'),
    borderRadius: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: Colors.themeGreen,
    paddingHorizontal: wp('3'),
    marginHorizontal: wp('1'),
    marginVertical: hp('.5'),
  },
});
